### PR TITLE
Updated config.example.js

### LINKED ISSUE #118: Update config.example.js file
Currently, the config.example.js has some commented code that must be uncommented for the app to work properly when someone builds the code locally.

This piece of code is currently present,
```
//   export const f = firebase;
//   export const database = firebase.database();
//   export const auth = firebase.auth();
//   export const storage = firebase.storage();
//   export const MAP_API = MAP_API_KEY;
```
it should be changed to this, to make instructions more precise.

```
//   After you fill the above details uncomment the below lines.
//   export const f = firebase;
//   export const database = firebase.database();
//   export const auth = firebase.auth();
//   export const storage = firebase.storage();
//   export const MAP_API = MAP_API_KEY;
```

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
I have updated config.example.js file to include more specific instruction on building the app locally. It will make the instructions more precise and prevent any confusion. Fixes #118

### CODE REVIEW

**Comment by Prakhar-Agarwal-byte** [comment]
I don't know why the build is failing as I have only added a comment.

**Comment by shehand** [comment]
Uncomment the export lines and commit the changes to the upstream. In a separate commit change the readme file and remove the sentence ", also uncomment the export lines below it to make them available to rest of the app." from the file.

**Comment by Prakhar-Agarwal-byte** [comment]
@shehand I have removed the line ", also uncomment the export lines below it to make them available to rest of the app." from the readme in separate PR #117. Please review it there.

**Review by shehand — DISMISSED** [review]

**Comment by shehand** [comment]
Please remove the previous commits that are not necessary as it does not reflect any changes but only increasing the commit history.

**Comment by Prakhar-Agarwal-byte** [comment]
@shehand Please see the changes now.

**Review by shehand — APPROVED** [review]

**Review by Danushka96 — APPROVED** [review]

**Pull request merged**
